version: '3.8'

services:
  db:
    image: postgres:15
    container_name: emagiz_db
    environment:
      POSTGRES_DB: emagiz_ticketing
      POSTGRES_USER: emagiz4
      POSTGRES_PASSWORD: emagiz4pass
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U emagiz4 -d emagiz_ticketing"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: emagiz_app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./target/ROOT.war:/usr/local/tomcat/webapps/ROOT.war

volumes:
  postgres_data: