version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    networks:
      - emagiz_network
    ports:
      - "8025:8025"
      - "1025:1025"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: emagiz_backend
    ports:
      - "8080:8080"
    networks:
      - emagiz_network
    depends_on:
      - mailhog

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: emagiz_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - emagiz_network

volumes:
  postgres_data:

networks:
  emagiz_network:
    driver: bridge
